name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test on NodeJS v${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.23.2

      - name: Install Dependancies
        run: pnpm i

      - name: Run Tests
        run: pnpm test
